FROM pytorch/pytorch:2.3.0-cuda12.1-cudnn8-runtime

WORKDIR /app

COPY model-server/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY model-server/ ./model_server/
COPY configs/ ./configs/

EXPOSE 8001

CMD ["uvicorn", "model_server.api.main:app", "--host", "0.0.0.0", "--port", "8001"]
